extends Node2D
## MainGame.gd — Root game scene controller.
##
## Owns the current map as a child and spawns the player.
## Map transitions are fully data-driven via WorldConnections:
##   - Walking off a map edge triggers a seamless connection transition.
##   - Stepping on a warp tile (door, cave, etc.) teleports the player.
##
## All connection and warp data comes from data/world_connections.json,
## generated by tools/build_world_connections.py.
##
## Zone systems wired here:
##   - EHI zone registration (seeds initial value from zone JSON on first visit)
##   - ZoneVisuals shader injection (TOZ visual states)
##   - BattleManager.battle_ended → PlayerParty state sync

const PLAYER_SCENE := preload("res://actors/player/Player.tscn")
const BATTLE_SCENE := preload("res://battle/ui/BattleScene.tscn")
const DEBUG_HUB_SCENE := preload("res://maps/debug_hub.tscn")

## Starting map (batch-painted scene).
const START_MAP := "res://maps/hoenn/cities/littleroot_town.tscn"
## Starting tile position inside that map (tile coordinates, 0-based).
const START_TILE := Vector2i(7, 12)

## Zone assignment data: pokeemerald MAP_ID → TOZ zone_id.
## Same file the batch painter uses; loaded once at startup.
const MAP_ZONE_IDS_PATH := "res://data/map_zone_ids.json"

var _active_maps: Dictionary = {} # map_id -> Node2D
var _player: CharacterBody2D = null

## The pokeemerald map ID for the map the player is currently "on", e.g. "MAP_LITTLEROOT_TOWN".
var _current_map_id: String = ""

## Tile dimensions of the current center map (in tiles), from WorldConnections.
var _map_size: Vector2i = Vector2i.ZERO

## Root node for all loaded maps to keep the scene tree organized.
var _map_container: Node2D = null

## Guard flag to prevent re-entrant transitions while a transition is in progress.
var _transitioning: bool = false

## Debug Hub state.
var _is_debug_hub: bool = false
var _last_location: Dictionary = {} # { "scene": String, "tile": Vector2i, "id": String }

## Tracks which zone_ids have had their initial EHI seeded this session.
## Prevents re-seeding on every re-entry.
var _ehi_seeded_zones: Array[String] = []

## Loaded from MAP_ZONE_IDS_PATH: pokeemerald MAP_ID → TOZ zone_id.
var _map_zone_ids: Dictionary = {}

# ─── Lifecycle ────────────────────────────────────────────────────────────────

func _ready() -> void:
	_load_map_zone_ids()
	
	_map_container = Node2D.new()
	_map_container.name = "MapNeighborhood"
	add_child(_map_container)
	
	BattleManager.battle_ended.connect(_on_battle_ended)
	RehabLog.milestone_reached.connect(_on_milestone_reached)
	RehabLog.zone_quelled.connect(_on_zone_quelled)
	
	_load_neighborhood_from_scene(START_MAP, START_TILE)
	
	PlayerParty.add_to_party("treecko", 5)
	PlayerParty.add_to_party("taillow", 5)
	add_child(BATTLE_SCENE.instantiate())


func _load_map_zone_ids() -> void:
	var f := FileAccess.open(MAP_ZONE_IDS_PATH, FileAccess.READ)
	if not f:
		push_warning("[MainGame] Cannot open " + MAP_ZONE_IDS_PATH)
		return
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	if parsed is Dictionary:
		_map_zone_ids = parsed
		print("[MainGame] Loaded %d zone assignments." % _map_zone_ids.size())


func _unhandled_input(event: InputEvent) -> void:
	if not (event is InputEventKey and event.pressed and not event.echo):
		return
	
	if event.keycode == KEY_F1:
		_toggle_debug_hub()
		get_viewport().set_input_as_handled()
		return

	match event.keycode:
		KEY_F2:
			print("Debug: Warping to Littleroot Town")
			_load_neighborhood_from_scene("res://maps/hoenn/cities/littleroot_town.tscn", START_TILE)
			get_viewport().set_input_as_handled()
		KEY_F3:
			print("Debug: Warping to Route 117")
			_load_neighborhood_from_scene("res://maps/hoenn/routes/route117.tscn", Vector2i(30, 5))
			get_viewport().set_input_as_handled()
		KEY_F5:
			print("Debug: Warping to Petalburg Woods (The Murk)")
			_load_neighborhood_from_scene("res://maps/hoenn/cities/petalburg_woods.tscn", Vector2i(24, 22))
			get_viewport().set_input_as_handled()
		KEY_F6:
			# Debug: cycle the current map's zone through infested → partial → restored → infested.
			# Useful for testing TOZ shader transitions and triage catch without walking around.
			var _zone: String = ZoneVisuals._primary_zone_id
			if _zone.is_empty():
				print("Debug: no active TOZ zone to cycle")
			else:
				var _cur: float = EHI.get_zone_ehi(_zone)
				var _target: float
				var _label: String
				if _cur < 34.0:
					_target = 50.0
					_label = "partial"
				elif _cur < 67.0:
					_target = 90.0
					_label = "restored"
				else:
					_target = 0.0
					_label = "infested"
				EHI.modify_zone_ehi(_zone, _target - _cur)
				print("Debug: %s EHI → %s (%.1f)" % [_zone, _label, _target])
			get_viewport().set_input_as_handled()


func _toggle_debug_hub() -> void:
	if _transitioning: return

	if not _is_debug_hub:
		# Save current location before switching.
		_last_location = {
			"scene": WorldConnections.get_scene_path(_current_map_id),
			"tile": Vector2i(_player.global_position / 16) if _player else START_TILE,
			"id": _current_map_id
		}
		_is_debug_hub = true

		# Clear existing neighborhood and player.
		for map_id in _active_maps:
			ZoneVisuals.clear_map(_active_maps[map_id])
			_active_maps[map_id].queue_free()
		_active_maps.clear()
		if _player:
			_player.queue_free()
			_player = null

		# Load the hub scene directly — it is not a pokeemerald map and has no
		# entry in world_connections.json, so we bypass _load_neighborhood entirely.
		var hub: Node2D = DEBUG_HUB_SCENE.instantiate()
		_map_container.add_child(hub)
		_active_maps["MAP_DEBUG_HUB"] = hub
		_current_map_id = "MAP_DEBUG_HUB"
		print("[MainGame] Entered Debug Hub.")
	else:
		# Return to last location.
		_is_debug_hub = false
		_load_neighborhood(_last_location.id, _last_location.tile)
		print("[MainGame] Returned from Debug Hub.")

# ─── Map Loading ──────────────────────────────────────────────────────────────

## Loads a map scene and spawns the player at the given tile position.
## tile_pos is in tile coordinates; multiply by 16 to get pixel position.
## map_id may be supplied when the caller already knows it (e.g. from a warp
## or edge-connection lookup), avoiding ambiguity when multiple maps share
## the same painted scene (e.g. the two Cycling Road entrances).
func _load_neighborhood_from_scene(scene_path: String, spawn_tile: Vector2i) -> void:
	var map_id = WorldConnections.get_map_id_for_scene(scene_path)
	if map_id.is_empty():
		push_error("MainGame: Unknown map scene: " + scene_path)
		return
	_load_neighborhood(map_id, spawn_tile)


func _load_neighborhood(center_map_id: String, spawn_tile: Vector2i) -> void:
	_transitioning = true
	
	# 1. Clear existing neighborhood
	for map_id in _active_maps:
		ZoneVisuals.clear_map(_active_maps[map_id])
		_active_maps[map_id].queue_free()
	_active_maps.clear()
	
	if _player:
		_player.queue_free()
		_player = null
	
	# 2. Load center map at (0,0)
	_current_map_id = center_map_id
	_map_size = WorldConnections.get_map_size(center_map_id)
	
	var center_node = _instantiate_map(center_map_id, Vector2.ZERO)
	if not center_node:
		_transitioning = false
		return
	
	# 3. Load neighbors
	_load_neighbors(center_map_id, Vector2.ZERO)
	
	# 4. Spawn player
	_player = PLAYER_SCENE.instantiate()
	add_child(_player)
	_player.z_index = 100 # Initial value; overridden every frame by Player.gd _physics_process
	_player.stepped_on_tile.connect(_on_stepped_on_tile)
	_player.interact_pressed.connect(func(tile: Vector2i) -> void:
		NPCSpawner.try_interact(tile, _player.global_position))
	
	# Tile-lock player to the spawn position and initialise discrete tile tracking.
	_player.set_tile(spawn_tile)

	# Give player a direct terrain reference so ledge behavior lookups never
	# accidentally resolve to a neighbor map's offset TileMapTerrain.
	_player.set_active_terrain(center_node.find_child("TileMapTerrain", true, false) as TileMap)

	# Register player camera for effects
	var cam := _player.get_node_or_null("Camera2D") as Camera2D
	ZoneVisuals.set_shake_camera(cam)
	
	# 5. Global visual sync
	var zone_id: String = center_node.get_meta("zone_id", "")
	_setup_zone_systems(zone_id) # Main zone
	
	# Apply shader to player
	var player_sprite := _player.get_node("AnimatedSprite2D") as CanvasItem
	ZoneVisuals.apply_to_canvas_item(player_sprite)
	
	_transitioning = false
	print("[MainGame] Neighborhood loaded for '%s'. %d maps active." % [center_map_id, _active_maps.size()])


func _load_neighbors(center_id: String, center_pos: Vector2) -> void:
	var center_size = WorldConnections.get_map_size(center_id)
	
	for dir in ["left", "right", "up", "down"]:
		var conn = WorldConnections.get_connection(center_id, dir)
		if conn.is_empty(): continue
		
		var dest_id = conn.get("map", "")
		var offset = int(conn.get("offset", 0))
		var dest_size = WorldConnections.get_map_size(dest_id)
		
		var dest_pos: Vector2
		match dir:
			"left": dest_pos = center_pos + Vector2(-dest_size.x * 16, offset * 16)
			"right": dest_pos = center_pos + Vector2(center_size.x * 16, offset * 16)
			"up": dest_pos = center_pos + Vector2(offset * 16, -dest_size.y * 16)
			"down": dest_pos = center_pos + Vector2(offset * 16, center_size.y * 16)
		
		if not _active_maps.has(dest_id):
			_instantiate_map(dest_id, dest_pos)


func _instantiate_map(map_id: String, pos: Vector2) -> Node2D:
	var scene_path = WorldConnections.get_scene_path(map_id)
	if scene_path.is_empty(): return null
	
	var map_scene = load(scene_path)
	if not map_scene: return null
	
	var map = map_scene.instantiate()
	_map_container.add_child(map)
	map.global_position = pos
	_active_maps[map_id] = map
	
	# Decoration always above characters (terrain=0, characters=1–200, decoration=500)
	var _deco := map.find_child("TileMapDecoration", true, false) as CanvasItem
	if _deco != null:
		_deco.z_index = 500
	AnimTileLoader.setup_map_animations(map)
	
	# Spawn NPCs for this map
	NPCSpawner.spawn_npcs_for_map(map_id, map)
	
	# Apply individual map visuals (corruption/bleed)
	var zone_id = map.get_meta("zone_id", "")
	if not zone_id.is_empty():
		_ensure_ehi_seeded(zone_id)
		ZoneVisuals.setup_for_map(map, zone_id)
	else:
		# If this map is a neighbor of the CURRENT center map, and center has a zone, bleed!
		var center_zone = ""
		if not _current_map_id.is_empty() and _active_maps.has(_current_map_id):
			center_zone = _active_maps[_current_map_id].get_meta("zone_id", "")
		
		# If not from center, maybe it's a neighbor of SOME zone map?
		# For now, simple center-bleed is enough for "seamless edges".
		if not center_zone.is_empty():
			ZoneVisuals.setup_for_map_bleed(map, center_zone)
		
	return map

# ─── Tile-Step Handler ────────────────────────────────────────────────────────

func _on_stepped_on_tile(tile_pos: Vector2i) -> void:
	if _transitioning or _current_map_id.is_empty():
		return

	# Notify zone visuals for step-based effects (poison flash, camera shake, etc.)
	ZoneVisuals.notify_zone_step()

	# ── 1. Map Focus Check (Seamless Transition) ───────────────────────────
	# If we are no longer on the "center" map, but we ARE on a loaded neighbor,
	# rotate the neighborhood focus.
	if not _is_tile_in_map(tile_pos, _current_map_id):
		for map_id in _active_maps:
			if map_id == _current_map_id: continue
			if _is_tile_in_map(tile_pos, map_id):
				_shift_focus_to(map_id)
				return

	# ── 2. Warp check (teleport like doors/caves) ─────────────────────────
	var warp := WorldConnections.get_warp_at(_current_map_id, tile_pos.x, tile_pos.y)
	if not warp.is_empty():
		var dest_map_id: String = warp.get("dest_map", "")
		var dest_warp_id: int = int(warp.get("dest_warp_id", -1))
		var arrival_tile: Vector2i = WorldConnections.get_warp_arrival_tile(dest_map_id, dest_warp_id)
		
		if arrival_tile == Vector2i(-1, -1):
			return

		print("[MainGame] Warp: %s → %s tile %s" % [_current_map_id, dest_map_id, arrival_tile])
		_load_neighborhood(dest_map_id, arrival_tile)
		return

func _is_tile_in_map(tile_pos: Vector2i, map_id: String) -> bool:
	var map = _active_maps.get(map_id)
	if not map: return false
	var origin = Vector2i(map.global_position / 16)
	var size = WorldConnections.get_map_size(map_id)
	return tile_pos.x >= origin.x and tile_pos.x < origin.x + size.x \
		and tile_pos.y >= origin.y and tile_pos.y < origin.y + size.y

func _shift_focus_to(new_map_id: String) -> void:
	print("[MainGame] Seamless Shift: %s → %s" % [_current_map_id, new_map_id])
	_current_map_id = new_map_id
	_map_size = WorldConnections.get_map_size(new_map_id)
	
	# Load new neighbors for the NEW center
	var center_node = _active_maps[new_map_id]
	_load_neighbors(new_map_id, center_node.global_position)

	# Keep the player's terrain reference pointed at the new center.
	if _player:
		_player.set_active_terrain(center_node.find_child("TileMapTerrain", true, false) as TileMap)
	
	# Drop maps that are no longer neighbors or active center
	var neighborhood = WorldConnections.get_all_adjacent_map_ids(new_map_id)
	neighborhood.append(new_map_id)
	
	var to_remove = []
	for map_id in _active_maps:
		if not map_id in neighborhood:
			to_remove.append(map_id)
	
	for map_id in to_remove:
		ZoneVisuals.clear_map(_active_maps[map_id])
		_active_maps[map_id].queue_free()
		_active_maps.erase(map_id)
	
	# Update global visuals (Fog/Weather) to match new center
	var center_zone: String = center_node.get_meta("zone_id", "")
	_setup_zone_systems(center_zone)
	
	# Update ALL loaded maps to ensure correct bleed/full shader based on new center
	for m_id in _active_maps:
		var m_node = _active_maps[m_id]
		var m_zone = m_node.get_meta("zone_id", "")
		if not m_zone.is_empty():
			ZoneVisuals.setup_for_map(m_node, m_zone)
		elif not center_zone.is_empty():
			ZoneVisuals.setup_for_map_bleed(m_node, center_zone)
		else:
			# Healthy map in a healthy neighborhood
			ZoneVisuals.setup_for_map(m_node, "")

# ─── Zone Systems ─────────────────────────────────────────────────────────────

## Configures global visual systems (primary zone, player shader, weather).
func _setup_zone_systems(zone_id: String) -> void:
	ZoneVisuals.set_primary_zone(zone_id)
	
	if _player:
		var sprite := _player.get_node("AnimatedSprite2D") as CanvasItem
		ZoneVisuals.apply_to_canvas_item(sprite)
	
	# Weather intensity follows the primary zone's EHI.
	if not zone_id.is_empty():
		ZoneVisuals.refresh_ehi()


## Seeds EHI from zone data on first visit this session (no-op on re-entry).
func _ensure_ehi_seeded(zone_id: String) -> void:
	if _ehi_seeded_zones.has(zone_id):
		return
	var initial_ehi: float = EncounterManager.get_zone_initial_ehi(zone_id)
	EHI.register_zone(zone_id, initial_ehi)
	_ehi_seeded_zones.append(zone_id)
	print("[MainGame] Seeded EHI for zone '%s' = %.1f." % [zone_id, initial_ehi])


# ─── Battle Result Sync ───────────────────────────────────────────────────────

## After a battle ends, sync the player's active Pokémon state from BattleManager
## back into PlayerParty so HP/status changes persist.
func _on_battle_ended(result: Dictionary) -> void:
	var outcome: String = result.get("outcome", "")
	if outcome == "flee":
		return # No state change on flee.
	# BattleManager._player_active holds the post-battle state.
	var post_state: Dictionary = BattleManager.get_player_active()
	if not post_state.is_empty():
		PlayerParty.update_active_state(post_state)
	print("[MainGame] Battle ended (%s) — party state synced." % outcome)


# ─── Debug Hotkeys ────────────────────────────────────────────────────────────


# ─── RehabLog Reward Handlers ─────────────────────────────────────────────────

## Fires on RehabLog.milestone_reached.
## Grants faction rep to both Aqua and Magma (no tension penalty — rehab work
## is neutral ground). Item rewards are deferred until the inventory system exists.
func _on_milestone_reached(milestone: int, _total: int) -> void:
	# Rep gain scales gently with milestone size, capped at 20.
	var rep_gain: float = minf(5.0 + float(milestone) * 0.1, 20.0)
	FactionManager.modify_rep("aqua", rep_gain, 0.0)
	FactionManager.modify_rep("magma", rep_gain, 0.0)

	var msg: String
	match milestone:
		1: msg = "Your first release was noticed. Both factions acknowledge your work."
		5: msg = "Five releases. The Ranger Network flags you as a field contributor."
		10: msg = "Ten releases. Hoenn's balance shifts — however slightly."
		25: msg = "Twenty-five releases. Archie and Maxie know your name."
		50: msg = "Fifty releases. Rayquaza stirs in the upper atmosphere."
		100: msg = "One hundred releases. You've changed something fundamental."
		_: msg = "Release milestone reached: %d total." % milestone

	DialogueManager.play_dialogue([msg], "Rehab Log")
	print("[MainGame] Milestone %d reward: +%.1f rep to both factions." % [milestone, rep_gain])


## Fires on RehabLog.zone_quelled (every quell release, including partial).
## Only delivers the full reward on completion (progress == 1.0).
func _on_zone_quelled(zone_id: String, _species_id: String, progress: float) -> void:
	if not is_equal_approx(progress, 1.0):
		return

	EHI.modify_zone_ehi(zone_id, 15.0)
	FactionManager.modify_rep("aqua", 10.0, 0.0)
	FactionManager.modify_rep("magma", 10.0, 0.0)

	var zone_display: String = zone_id.replace("_", " ").capitalize()
	DialogueManager.play_dialogue([
		"The %s has been fully quelled!" % zone_display,
		"Ecological harmony is returning to the region. Both factions send their thanks.",
	], "Rehab Log")
	print("[MainGame] Zone '%s' fully quelled — EHI +15, +10 rep both factions." % zone_id)
