extends Node2D
## MainGame.gd — Root game scene controller.
##
## Owns the current map as a child and spawns the player.
## Map transitions are fully data-driven via WorldConnections:
##   - Walking off a map edge triggers a seamless connection transition.
##   - Stepping on a warp tile (door, cave, etc.) teleports the player.
##
## All connection and warp data comes from data/world_connections.json,
## generated by tools/build_world_connections.py.
##
## Zone systems wired here:
##   - EHI zone registration (seeds initial value from zone JSON on first visit)
##   - ZoneVisuals shader injection (TOZ visual states)
##   - BattleManager.battle_ended → PlayerParty state sync

const PLAYER_SCENE  := preload("res://actors/player/Player.tscn")
const BATTLE_SCENE  := preload("res://battle/ui/BattleScene.tscn")

## Starting map (batch-painted scene).
const START_MAP  := "res://maps/hoenn/cities/littleroot_town.tscn"
## Starting tile position inside that map (tile coordinates, 0-based).
const START_TILE := Vector2i(7, 12)

## Zone assignment data: pokeemerald MAP_ID → TOZ zone_id.
## Same file the batch painter uses; loaded once at startup.
const MAP_ZONE_IDS_PATH := "res://data/map_zone_ids.json"

var _current_map: Node2D = null
var _player: CharacterBody2D = null

## The pokeemerald map ID for the currently loaded scene, e.g. "MAP_LITTLEROOT_TOWN".
var _current_map_id: String = ""

## Tile dimensions of the current map (in tiles), from WorldConnections.
var _map_size: Vector2i = Vector2i.ZERO

## Guard flag to prevent re-entrant transitions while a transition is in progress.
var _transitioning: bool = false

## Tracks which zone_ids have had their initial EHI seeded this session.
## Prevents re-seeding on every re-entry.
var _ehi_seeded_zones: Array[String] = []

## Loaded from MAP_ZONE_IDS_PATH: pokeemerald MAP_ID → TOZ zone_id.
var _map_zone_ids: Dictionary = {}

# ─── Lifecycle ────────────────────────────────────────────────────────────────

func _ready() -> void:
	_load_map_zone_ids()
	BattleManager.battle_ended.connect(_on_battle_ended)
	RehabLog.milestone_reached.connect(_on_milestone_reached)
	RehabLog.zone_quelled.connect(_on_zone_quelled)
	_load_map(START_MAP, START_TILE)
	PlayerParty.add_to_party("treecko", 5)
	PlayerParty.add_to_party("taillow", 5)
	add_child(BATTLE_SCENE.instantiate())


func _load_map_zone_ids() -> void:
	var f := FileAccess.open(MAP_ZONE_IDS_PATH, FileAccess.READ)
	if not f:
		push_warning("[MainGame] Cannot open " + MAP_ZONE_IDS_PATH)
		return
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	if parsed is Dictionary:
		_map_zone_ids = parsed
		print("[MainGame] Loaded %d zone assignments." % _map_zone_ids.size())

# ─── Map Loading ──────────────────────────────────────────────────────────────

## Loads a map scene and spawns the player at the given tile position.
## tile_pos is in tile coordinates; multiply by 16 to get pixel position.
## map_id may be supplied when the caller already knows it (e.g. from a warp
## or edge-connection lookup), avoiding ambiguity when multiple maps share
## the same painted scene (e.g. the two Cycling Road entrances).
func _load_map(scene_path: String, spawn_tile: Vector2i, map_id: String = "") -> void:
	_transitioning = true

	# Remove previous map and player.
	if _current_map:
		_current_map.queue_free()
		_current_map = null
	if _player:
		_player.queue_free()
		_player = null

	# Load and instantiate the new map.
	var map_scene: PackedScene = load(scene_path)
	if map_scene == null:
		push_error("MainGame: Failed to load map scene: " + scene_path)
		_transitioning = false
		return
	_current_map = map_scene.instantiate()
	add_child(_current_map)
	# Decoration always above characters: z=100 >> any Y-sorted character z (tile_row+1 ≈ 0–80).
	var _deco := _current_map.find_child("TileMapDecoration", true, false) as CanvasItem
	if _deco != null:
		_deco.z_index = 100
	AnimTileLoader.setup_map_animations(_current_map)

	# Resolve map ID and dimensions from world data.
	# Prefer the caller-supplied id; fall back to reverse scene lookup.
	_current_map_id = map_id if not map_id.is_empty() \
		else WorldConnections.get_map_id_for_scene(scene_path)
	_map_size       = WorldConnections.get_map_size(_current_map_id) \
		if not _current_map_id.is_empty() else Vector2i.ZERO

	# Spawn the player.
	_player = PLAYER_SCENE.instantiate()
	add_child(_player)
	_player.stepped_on_tile.connect(_on_stepped_on_tile)
	_player.interact_pressed.connect(func(tile: Vector2i) -> void:
		NPCSpawner.try_interact(tile, _player.global_position))

	# Position player at the centre of the spawn tile.
	_player.global_position = Vector2(spawn_tile) * 16.0 + Vector2(8.0, 8.0)

	# Spawn NPCs for this map.
	NPCSpawner.spawn_npcs_for_map(_current_map_id, _current_map)

	# ── Zone systems: EHI seeding + TOZ visual shader ─────────────────────────
	var zone_id: String = _current_map.get_meta("zone_id", "")
	_setup_zone_systems(zone_id)

	# Apply TOZ shader to the player sprite so they blend into the zone.
	var player_sprite := _player.get_node("AnimatedSprite2D") as CanvasItem
	ZoneVisuals.apply_to_canvas_item(player_sprite)

	# Register the player camera so ZoneVisuals can shake it on flash peaks.
	var cam := _player.get_node_or_null("Camera2D") as Camera2D
	ZoneVisuals.set_shake_camera(cam)

	_transitioning = false
	print("[MainGame] Loaded '%s'  map_id=%s  size=%s  spawn=%s  zone=%s" \
		% [scene_path.get_file(), _current_map_id, _map_size, spawn_tile, zone_id])

# ─── Tile-Step Handler ────────────────────────────────────────────────────────

func _on_stepped_on_tile(tile_pos: Vector2i) -> void:
	if _transitioning or _current_map_id.is_empty():
		return

	# Notify zone visuals for step-based effects (poison flash, camera shake, etc.)
	ZoneVisuals.notify_zone_step()

	# ── 1. Warp check (door / cave entrance) ──────────────────────────────
	var warp := WorldConnections.get_warp_at(_current_map_id, tile_pos.x, tile_pos.y)
	if not warp.is_empty():
		var dest_map_id: String = warp.get("dest_map", "")
		var dest_warp_id: int   = int(warp.get("dest_warp_id", -1))
		var dest_scene: String  = WorldConnections.get_scene_path(dest_map_id)

		if dest_scene.is_empty():
			push_warning("[MainGame] Warp to '%s' has no painted scene yet." % dest_map_id)
			return

		var arrival_tile: Vector2i = WorldConnections.get_warp_arrival_tile(dest_map_id, dest_warp_id)
		if arrival_tile == Vector2i(-1, -1):
			push_warning("[MainGame] No arrival tile for warp_id %d in '%s'." \
				% [dest_warp_id, dest_map_id])
			return

		print("[MainGame] Warp: %s → %s tile %s" % [_current_map_id, dest_map_id, arrival_tile])
		_load_map(dest_scene, arrival_tile, dest_map_id)
		return

	# ── 2. Map-edge connection check ───────────────────────────────────────
	if _map_size == Vector2i.ZERO:
		return  # No dimension data; can't detect edges.

	var direction := ""
	var perp_coord := 0

	if tile_pos.x < 0:
		direction  = "left"
		perp_coord = tile_pos.y
	elif tile_pos.x >= _map_size.x:
		direction  = "right"
		perp_coord = tile_pos.y
	elif tile_pos.y < 0:
		direction  = "up"
		perp_coord = tile_pos.x
	elif tile_pos.y >= _map_size.y:
		direction  = "down"
		perp_coord = tile_pos.x

	if direction.is_empty():
		return

	var conn := WorldConnections.get_connection(_current_map_id, direction)
	if conn.is_empty():
		return  # No connection in that direction.

	var dest_map_id: String = conn.get("map", "")
	var offset: int         = int(conn.get("offset", 0))
	var dest_scene: String  = WorldConnections.get_scene_path(dest_map_id)

	if dest_scene.is_empty():
		push_warning("[MainGame] Connection to '%s' has no painted scene yet." % dest_map_id)
		return

	var dest_size: Vector2i = WorldConnections.get_map_size(dest_map_id)
	var arrival_tile: Vector2i

	match direction:
		"left":
			arrival_tile = Vector2i(dest_size.x - 1, perp_coord - offset)
		"right":
			arrival_tile = Vector2i(0, perp_coord - offset)
		"up":
			arrival_tile = Vector2i(perp_coord - offset, dest_size.y - 1)
		"down":
			arrival_tile = Vector2i(perp_coord - offset, 0)
		"dive", "emerge":
			arrival_tile = tile_pos  # same XY, different map depth

	print("[MainGame] Edge (%s): %s → %s tile %s" \
		% [direction, _current_map_id, dest_map_id, arrival_tile])
	_load_map(dest_scene, arrival_tile, dest_map_id)

# ─── Zone Systems ─────────────────────────────────────────────────────────────

## Seeds EHI for a zone on first visit (using initial value from zone JSON),
## then applies the TOZ shader via ZoneVisuals.
## For non-TOZ maps adjacent to a TOZ, applies a bleed shader at one stage lower.
func _setup_zone_systems(zone_id: String) -> void:
	if zone_id.is_empty():
		# Not a primary TOZ — check for bleed from an adjacent TOZ map.
		var bleed_zone: String = _find_adjacent_bleed_zone()
		if not bleed_zone.is_empty():
			_ensure_ehi_seeded(bleed_zone)
			ZoneVisuals.setup_for_map_bleed(_current_map, bleed_zone)
		else:
			ZoneVisuals.setup_for_map(_current_map, "")
		return

	# Primary TOZ: seed EHI + apply full shader.
	_ensure_ehi_seeded(zone_id)
	ZoneVisuals.setup_for_map(_current_map, zone_id)


## Seeds EHI from zone data on first visit this session (no-op on re-entry).
func _ensure_ehi_seeded(zone_id: String) -> void:
	if _ehi_seeded_zones.has(zone_id):
		return
	var initial_ehi: float = EncounterManager.get_zone_initial_ehi(zone_id)
	EHI.register_zone(zone_id, initial_ehi)
	_ehi_seeded_zones.append(zone_id)
	print("[MainGame] Seeded EHI for zone '%s' = %.1f." % [zone_id, initial_ehi])


## Returns the zone_id of any TOZ map directly adjacent (via warp or edge)
## to the current map, or "" if none exists.
func _find_adjacent_bleed_zone() -> String:
	if _current_map_id.is_empty():
		return ""
	var adjacent: Array[String] = WorldConnections.get_all_adjacent_map_ids(_current_map_id)
	for adj_id: String in adjacent:
		var zone: String = _map_zone_ids.get(adj_id, "")
		if not zone.is_empty():
			return zone
	return ""


# ─── Battle Result Sync ───────────────────────────────────────────────────────

## After a battle ends, sync the player's active Pokémon state from BattleManager
## back into PlayerParty so HP/status changes persist.
func _on_battle_ended(result: Dictionary) -> void:
	var outcome: String = result.get("outcome", "")
	if outcome == "flee":
		return  # No state change on flee.
	# BattleManager._player_active holds the post-battle state.
	var post_state: Dictionary = BattleManager.get_player_active()
	if not post_state.is_empty():
		PlayerParty.update_active_state(post_state)
	print("[MainGame] Battle ended (%s) — party state synced." % outcome)


# ─── Debug Hotkeys ────────────────────────────────────────────────────────────

func _unhandled_input(event: InputEvent) -> void:
	if not (event is InputEventKey and event.pressed and not event.echo):
		return
	match event.keycode:
		KEY_F1:
			print("Debug: Warping to Route 113")
			_load_map("res://maps/hoenn/routes/route113.tscn", Vector2i(5, 10))
			get_viewport().set_input_as_handled()
		KEY_F2:
			print("Debug: Warping to Littleroot Town")
			_load_map("res://maps/hoenn/cities/littleroot_town.tscn", START_TILE)
			get_viewport().set_input_as_handled()
		KEY_F3:
			print("Debug: Warping to Route 117")
			_load_map("res://maps/hoenn/routes/route117.tscn", Vector2i(30, 5))
			get_viewport().set_input_as_handled()
		KEY_F5:
			print("Debug: Warping to Petalburg Woods (The Murk)")
			_load_map("res://maps/hoenn/cities/petalburg_woods.tscn", Vector2i(24, 22))
			get_viewport().set_input_as_handled()
		KEY_F6:
			# Debug: cycle The Murk through infested → partial → restored → infested.
			# Useful for testing triage catch (needs infested) and TOZ shader transitions.
			var _cur: float = EHI.get_zone_ehi("the_murk")
			var _target: float
			var _label: String
			if _cur < 34.0:
				_target = 50.0
				_label  = "partial"
			elif _cur < 67.0:
				_target = 90.0
				_label  = "restored"
			else:
				_target = 0.0
				_label  = "infested"
			EHI.modify_zone_ehi("the_murk", _target - _cur)
			print("Debug: Murk EHI → %s (%.1f)" % [_label, _target])
			get_viewport().set_input_as_handled()


# ─── RehabLog Reward Handlers ─────────────────────────────────────────────────

## Fires on RehabLog.milestone_reached.
## Grants faction rep to both Aqua and Magma (no tension penalty — rehab work
## is neutral ground). Item rewards are deferred until the inventory system exists.
func _on_milestone_reached(milestone: int, _total: int) -> void:
	# Rep gain scales gently with milestone size, capped at 20.
	var rep_gain: float = minf(5.0 + float(milestone) * 0.1, 20.0)
	FactionManager.modify_rep("aqua", rep_gain, 0.0)
	FactionManager.modify_rep("magma", rep_gain, 0.0)

	var msg: String
	match milestone:
		1:   msg = "Your first release was noticed. Both factions acknowledge your work."
		5:   msg = "Five releases. The Ranger Network flags you as a field contributor."
		10:  msg = "Ten releases. Hoenn's balance shifts — however slightly."
		25:  msg = "Twenty-five releases. Archie and Maxie know your name."
		50:  msg = "Fifty releases. Rayquaza stirs in the upper atmosphere."
		100: msg = "One hundred releases. You've changed something fundamental."
		_:   msg = "Release milestone reached: %d total." % milestone

	DialogueManager.play_dialogue([msg], "Rehab Log")
	print("[MainGame] Milestone %d reward: +%.1f rep to both factions." % [milestone, rep_gain])


## Fires on RehabLog.zone_quelled (every quell release, including partial).
## Only delivers the full reward on completion (progress == 1.0).
func _on_zone_quelled(zone_id: String, _species_id: String, progress: float) -> void:
	if not is_equal_approx(progress, 1.0):
		return

	EHI.modify_zone_ehi(zone_id, 15.0)
	FactionManager.modify_rep("aqua", 10.0, 0.0)
	FactionManager.modify_rep("magma", 10.0, 0.0)

	var zone_display: String = zone_id.replace("_", " ").capitalize()
	DialogueManager.play_dialogue([
		"The %s has been fully quelled!" % zone_display,
		"Ecological harmony is returning to the region. Both factions send their thanks.",
	], "Rehab Log")
	print("[MainGame] Zone '%s' fully quelled — EHI +15, +10 rep both factions." % zone_id)
