extends Node
## WorldConnections — autoload that provides map connection and warp data
## derived from pokeemerald's map.json files.
##
## Source of truth: res://data/world_connections.json
## (generated by tools/build_world_connections.py)
##
## Usage (from anywhere):
##   WorldConnections.get_warp_at("MAP_ROUTE117", 51, 5)
##   WorldConnections.get_connection("MAP_ROUTE117", "right")
##   WorldConnections.get_scene_path("MAP_MAUVILLE_CITY")

const DATA_PATH := "res://data/world_connections.json"

var _maps: Dictionary = {}          # map_id → entry dict
var _scene_to_map: Dictionary = {}  # scene_path → map_id

# ─────────────────────────────────────────────────────────────────────────────
func _ready() -> void:
	var f := FileAccess.open(DATA_PATH, FileAccess.READ)
	if not f:
		push_error("WorldConnections: cannot open " + DATA_PATH)
		return
	var parsed = JSON.parse_string(f.get_as_text())
	f.close()
	if not parsed or not parsed.has("maps"):
		push_error("WorldConnections: invalid JSON in " + DATA_PATH)
		return
	_maps        = parsed["maps"]
	_scene_to_map = parsed.get("scene_to_map", {})
	print("[WorldConnections] Loaded %d maps, %d scene paths." \
		% [_maps.size(), _scene_to_map.size()])


# ── Public API ────────────────────────────────────────────────────────────────

## Returns the map ID for a given scene path, or "" if unknown.
func get_map_id_for_scene(scene_path: String) -> String:
	return _scene_to_map.get(scene_path, "")


## Returns the scene path for a given map ID, or "" if unknown / not painted.
func get_scene_path(map_id: String) -> String:
	var entry: Dictionary = _maps.get(map_id, {})
	return entry.get("scene_path", "")


## Returns the tile dimensions of a map as Vector2i(width, height).
## Returns Vector2i.ZERO if the map has no layout data.
func get_map_size(map_id: String) -> Vector2i:
	var entry: Dictionary = _maps.get(map_id, {})
	if entry.is_empty():
		return Vector2i.ZERO
	return Vector2i(int(entry.get("width", 0)), int(entry.get("height", 0)))


## Returns the connection dict {map, offset} for the given direction,
## or {} if no connection exists.
func get_connection(map_id: String, direction: String) -> Dictionary:
	var entry: Dictionary = _maps.get(map_id, {})
	for conn: Dictionary in entry.get("connections", []):
		if conn.get("direction", "") == direction:
			return conn
	return {}


## Returns the first warp dict {x, y, dest_map, dest_warp_id} at tile (tx, ty),
## or {} if none. dest_warp_id is -1 for dynamic warps.
func get_warp_at(map_id: String, tx: int, ty: int) -> Dictionary:
	var entry: Dictionary = _maps.get(map_id, {})
	for warp: Dictionary in entry.get("warps", []):
		if int(warp.get("x", -1)) == tx and int(warp.get("y", -1)) == ty:
			return warp
	return {}


## Returns every map ID directly reachable from [param map_id] via warps or
## edge connections.  Used by MainGame to detect TOZ bleed zones.
## Duplicate entries are deduplicated; the source map itself is excluded.
func get_all_adjacent_map_ids(map_id: String) -> Array[String]:
	var entry: Dictionary = _maps.get(map_id, {})
	var seen: Dictionary  = {}
	var result: Array[String] = []
	for warp: Dictionary in entry.get("warps", []):
		var dest: String = warp.get("dest_map", "")
		if not dest.is_empty() and dest != map_id and not seen.has(dest):
			seen[dest] = true
			result.append(dest)
	for conn: Dictionary in entry.get("connections", []):
		var dest: String = conn.get("map", "")
		if not dest.is_empty() and dest != map_id and not seen.has(dest):
			seen[dest] = true
			result.append(dest)
	return result


## Returns the tile position where the player should arrive when warping to
## map_id at warp index warp_idx.
## Returns Vector2i(-1, -1) if not found.
func get_warp_arrival_tile(map_id: String, warp_idx: int) -> Vector2i:
	if warp_idx < 0:
		return Vector2i(-1, -1)
	var entry: Dictionary = _maps.get(map_id, {})
	var warps: Array = entry.get("warps", [])
	if warp_idx >= warps.size():
		return Vector2i(-1, -1)
	var w: Dictionary = warps[warp_idx]
	return Vector2i(int(w.get("x", 0)), int(w.get("y", 0)))
