extends Node2D

@onready var camera: Camera2D = $Camera
@onready var labels_node: Node2D = $Labels
@onready var displays_node: Node2D = $Displays
@onready var search_edit: LineEdit = $UI/Panel/HBox/SearchEdit
@onready var filter_option: OptionButton = $UI/Panel/HBox/FilterOption
@onready var status_label: Label = $UI/Panel/HBox/StatusLabel

const POKEEMERALD_BASE = "C:/Users/levib/pokemon_projects/pokeemerald/"

const TOZ_WARPS = {
	# Spawn positions derived from actual warp tile coordinates in world_connections.json,
	# offset a few tiles inward so the player doesn't immediately re-trigger a warp.
	"ashen_glacier": {"name": "Ashen Glacier", "path": "res://maps/hoenn/routes/route113.tscn", "pos": Vector2i(33, 8), "id": "MAP_ROUTE113"},
	"static_sprawl": {"name": "Static Sprawl", "path": "res://maps/hoenn/cities/mauville_city.tscn", "pos": Vector2i(22, 10), "id": "MAP_MAUVILLE_CITY"},
	"emberscar": {"name": "Emberscar", "path": "res://maps/hoenn/routes/route112.tscn", "pos": Vector2i(20, 35), "id": "MAP_ROUTE112"},
	"the_veil": {"name": "The Veil", "path": "res://maps/hoenn/cities/mossdeep_city.tscn", "pos": Vector2i(38, 15), "id": "MAP_MOSSDEEP_CITY"},
	"dread_shore": {"name": "Dread Shore", "path": "res://maps/hoenn/routes/route122.tscn", "pos": Vector2i(22, 25), "id": "MAP_ROUTE122"},
	"the_murk": {"name": "The Murk", "path": "res://maps/hoenn/cities/petalburg_woods.tscn", "pos": Vector2i(24, 22), "id": "MAP_PETALBURG_WOODS"},
	"the_crucible": {"name": "The Crucible", "path": "res://maps/hoenn/routes/route111.tscn", "pos": Vector2i(20, 23), "id": "MAP_ROUTE111"},
	"the_overgrowth": {"name": "The Overgrowth", "path": "res://maps/hoenn/routes/route119.tscn", "pos": Vector2i(12, 36), "id": "MAP_ROUTE119"},
	"abyss_bloom": {"name": "Abyss Bloom", "path": "res://maps/hoenn/cities/sootopolis_city.tscn", "pos": Vector2i(31, 35), "id": "MAP_SOOTOPOLIS_CITY"},
	"static_sky": {"name": "Static Sky", "path": "res://maps/hoenn/routes/route131.tscn", "pos": Vector2i(30, 15), "id": "MAP_ROUTE131"},
}

var _items: Array[Node2D] = []
var _panning: bool = false
var _min_zoom: float = 0.1
var _max_zoom: float = 10.0

func _ready():
	# The player's Camera2D is freed before the hub loads; make this
	# camera current so the viewport isn't left with no active camera.
	camera.make_current()

	_build_ui_layout()
	_populate_database()

	search_edit.text_changed.connect(_on_search_changed)
	filter_option.item_selected.connect(_on_filter_changed)

	_refresh_grid()

func _build_ui_layout():
	var bg := ColorRect.new()
	bg.size = Vector2(10000, 10000)
	bg.position = Vector2(-5000, -5000)
	bg.color = Color(0.08, 0.08, 0.1, 1.0)
	bg.mouse_filter = Control.MOUSE_FILTER_IGNORE
	add_child(bg)
	move_child(bg, 0)

func _populate_database():
	# 1. Species Audit — read from assets/sprites/pokemon/ (ground truth for what's in-game).
	# Sprites are ported from sprites-master via tools/port_sprites_from_master.py.
	var sprite_assets = "res://assets/sprites/pokemon/"
	var d = DirAccess.open(sprite_assets)
	if d:
		d.list_dir_begin()
		var n = d.get_next()
		while n != "":
			if d.current_is_dir() and not n.begins_with("."):
				_create_db_entry(n, "species", "pokemon")
			n = d.get_next()

	# 2. Tileset Audit — read from assets/tilesets/ (generated by build_godot_tilesets.py).
	var ts_assets = "res://assets/tilesets/"
	var d2 = DirAccess.open(ts_assets)
	if d2:
		d2.list_dir_begin()
		var n2 = d2.get_next()
		while n2 != "":
			# Only list _bottom.png files to avoid duplicate entries per tileset.
			if not d2.current_is_dir() and n2.ends_with("_bottom.png"):
				var ts_id = n2.replace("_bottom.png", "")
				_create_db_entry(ts_id, "tileset", "")
			n2 = d2.get_next()

	# 3. TOZ Warps
	for zone_id in TOZ_WARPS.keys():
		_create_db_entry(zone_id, "warp", "")

func _create_db_entry(id: String, category: String, sub_type: String):
	var node = Node2D.new()
	node.set_meta("id", id)
	node.set_meta("category", category)
	node.name = "entry_%s" % id
	
	displays_node.add_child(node)
	_items.append(node)
	
	var bg = ColorRect.new()
	bg.size = Vector2(100, 100)
	bg.color = Color(1, 1, 1, 0.05)
	node.add_child(bg)
	
	var label = Label.new()
	label.text = id if category != "warp" else TOZ_WARPS[id].name
	label.scale = Vector2(0.5, 0.5)
	label.position = Vector2(0, 105)
	node.add_child(label)
	
	match category:
		"species":
			# Check both ported sprite and sprites-master emerald source.
			var ported_path = "res://assets/sprites/pokemon/%s/front.png" % id
			var sprite = Sprite2D.new()
			if FileAccess.file_exists(ported_path):
				sprite.texture = load(ported_path)
				sprite.position = Vector2(50, 50)
				node.add_child(sprite)
			else:
				_add_missing_tag(node)
				node.add_child(sprite)
		"tileset":
			# Tilesets are named {ts_id}_bottom.png — id already has the full name.
			var godot_path = "res://assets/tilesets/%s_bottom.png" % id
			var sprite = Sprite2D.new()
			if FileAccess.file_exists(godot_path):
				sprite.texture = load(godot_path)
				sprite.scale = Vector2(0.15, 0.15)
				sprite.centered = false
				sprite.position = Vector2(5, 5)
				node.add_child(sprite)
			else:
				_add_missing_tag(node)
				node.add_child(sprite)
		"warp":
			var btn = Button.new()
			btn.text = "WARP"
			btn.custom_minimum_size = Vector2(80, 30)
			btn.position = Vector2(10, 35)
			btn.pressed.connect(_on_warp_pressed.bind(id))
			node.add_child(btn)

func _add_missing_tag(node: Node2D):
	var m = ColorRect.new()
	m.size = Vector2(80, 20)
	m.color = Color(0.8, 0, 0, 0.5)
	m.position = Vector2(10, 40)
	node.add_child(m)
	var l = Label.new()
	l.text = "MISSING"
	l.scale = Vector2(0.4, 0.4)
	l.position = Vector2(15, 42)
	node.add_child(l)

func _refresh_grid():
	var search_query = search_edit.text.to_lower()
	var filter_idx = filter_option.selected
	
	var x = 0
	var y = 0
	var offset_x = 150
	var offset_y = 150
	var max_width = 1600
	var visible_count = 0
	
	for item in _items:
		var item_id = item.get_meta("id").to_lower()
		var item_cat = item.get_meta("category")
		
		var matches_search = search_query == "" or search_query in item_id
		var matches_cat = false
		if filter_idx == 0: matches_cat = true
		elif filter_idx == 1 and item_cat == "species": matches_cat = true
		elif filter_idx == 2 and item_cat == "tileset": matches_cat = true
		elif filter_idx == 3 and item_cat == "warp": matches_cat = true
		
		if matches_search and matches_cat:
			item.visible = true
			item.position = Vector2(x + 50, y + 100)
			visible_count += 1
			x += offset_x
			if x > max_width:
				x = 0
				y += offset_y
		else:
			item.visible = false

	status_label.text = "Items: %d / %d" % [visible_count, _items.size()]

func _on_search_changed(_new_text: String):
	_refresh_grid()

func _on_filter_changed(_idx: int):
	_refresh_grid()

func _on_warp_pressed(zone_id: String):
	# DebugHub → MapNeighborhood (_map_container) → MainGame
	var main: Node = get_parent().get_parent()
	var data = TOZ_WARPS[zone_id]
	main._is_debug_hub = false
	main._load_neighborhood(data.id, data.pos)
	print("[DebugHub] Warped to %s" % data.name)

# ─── Camera Controls ─────────────────────────────────────────────────────────

func _input(event: InputEvent):
	# Using _input instead of _unhandled_input to ensure we catch events
	# But we must be careful not to block UI input.
	if event is InputEventMouseButton:
		if event.button_index == MOUSE_BUTTON_WHEEL_UP:
			_zoom_camera(1.1, event.position)
		elif event.button_index == MOUSE_BUTTON_WHEEL_DOWN:
			_zoom_camera(0.9, event.position)
		elif event.button_index == MOUSE_BUTTON_RIGHT or event.button_index == MOUSE_BUTTON_MIDDLE:
			_panning = event.pressed
	
	elif event is InputEventMouseMotion and _panning:
		camera.position -= event.relative / camera.zoom

func _zoom_camera(factor: float, _mouse_pos: Vector2):
	var mouse_world_start = get_global_mouse_position()
	
	var next_zoom = camera.zoom * factor
	if next_zoom.x < _min_zoom: next_zoom = Vector2(_min_zoom, _min_zoom)
	if next_zoom.x > _max_zoom: next_zoom = Vector2(_max_zoom, _max_zoom)
	camera.zoom = next_zoom
	
	var mouse_world_end = get_global_mouse_position()
	camera.position += (mouse_world_start - mouse_world_end)
