#!/usr/bin/env python3
"""
generate_debug_spawner.py — Godot Integration Doctor
Generates a debug auto-spawner script for a map scene so it can be tested standalone.

Usage:
    python3 generate_debug_spawner.py /path/to/map_scene.tscn [--player-scene res://actors/player/Player.tscn]

Generates a .gd script that:
1. Checks if a MainGame controller is present (i.e., running via the main scene)
2. If not, instantiates the Player scene and positions it at the first WarpPoint
3. Prints a debug message so you know the auto-spawner is active

The script is designed to be attached to the map root node ONLY during development.
Remove it (or the autoload check will skip it) before shipping.
"""

import os
import re
import sys
from pathlib import Path


def parse_map_metadata(tscn_path: str) -> dict:
    """Extract root node metadata from a .tscn file."""
    metadata = {}
    root_name = "MapRoot"
    root_script = None
    in_root = False

    with open(tscn_path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            line = line.strip()

            # Find root node (parent="" or no parent attribute)
            if line.startswith('[node name="') and ('parent="' not in line or 'parent=""' in line):
                match = re.match(r'\[node\s+name="([^"]+)"', line)
                if match:
                    root_name = match.group(1)
                    in_root = True
                continue

            # Next node starts — stop reading root properties
            if in_root and line.startswith("[node "):
                in_root = False
                continue

            if in_root:
                # Check for script on a separate line
                script_match = re.match(r'script\s*=\s*ExtResource\("([^"]+)"\)', line)
                if script_match:
                    root_script = script_match.group(1)

                meta_match = re.match(r'metadata/(\w+)\s*=\s*(.*)', line)
                if meta_match:
                    metadata[meta_match.group(1)] = meta_match.group(2).strip()

    return {
        "root_name": root_name,
        "root_script": root_script,
        "metadata": metadata,
    }


def generate_spawner_script(
    map_info: dict,
    player_scene_path: str = "res://actors/player/Player.tscn",
    controller_node: str = "MainGame",
) -> str:
    """Generate the GDScript debug spawner."""

    map_dims = map_info["metadata"].get("map_dimensions_px", "Vector2i(640, 400)")

    script = f'''## Debug auto-spawner for standalone map testing.
## Attach this to the map root node. When running the map scene directly (F6),
## this script auto-spawns a Player instance so you can walk around and test.
## When running via the main game scene (F5), it does nothing.
##
## Generated by: godot-integration-doctor/scripts/generate_debug_spawner.py
## Safe to remove before shipping.
extends Node2D

const _PLAYER_SCENE := preload("{player_scene_path}")
const _CONTROLLER_NAME := "{controller_node}"

func _ready() -> void:
\t# If the main game controller is running, it handles player spawning — do nothing.
\tif get_tree().root.has_node(_CONTROLLER_NAME):
\t\treturn

\t# Standalone mode: spawn a player for testing.
\tvar player := _PLAYER_SCENE.instantiate()
\tadd_child(player)

\t# Try to position at the first WarpPoint.
\tvar warp_container := find_child("WarpPoints", true, false)
\tif warp_container and warp_container.get_child_count() > 0:
\t\tvar first_warp: Node2D = warp_container.get_child(0) as Node2D
\t\tif first_warp:
\t\t\tplayer.global_position = first_warp.global_position
\t\t\tprint("[DebugSpawner] Player placed at warp: %s (%s)" % [first_warp.name, first_warp.global_position])
\telse:
\t\t# Fallback: center of the map
\t\tvar dims := {map_dims}
\t\tplayer.global_position = Vector2(dims.x / 2.0, dims.y / 2.0)
\t\tprint("[DebugSpawner] Player placed at map center: %s" % player.global_position)

\tprint("[DebugSpawner] Standalone mode active for scene: {map_info['root_name']}")
'''

    # If the root already has a script, warn and generate as a child-node script instead
    if map_info.get("root_script"):
        script = f'''## Debug auto-spawner for standalone map testing.
## The map root already has a script ({map_info['root_script']}),
## so this should be attached to a NEW child Node2D named "DebugSpawner".
##
## In the .tscn, add:
##   [node name="DebugSpawner" type="Node2D" parent="."]
##   script = ExtResource("debug_spawner_script_id")
##
## Generated by: godot-integration-doctor/scripts/generate_debug_spawner.py
## Safe to remove before shipping.
extends Node2D

const _PLAYER_SCENE := preload("{player_scene_path}")
const _CONTROLLER_NAME := "{controller_node}"

func _ready() -> void:
\tif get_tree().root.has_node(_CONTROLLER_NAME):
\t\treturn

\tvar player := _PLAYER_SCENE.instantiate()
\tget_parent().add_child(player)

\tvar warp_container := get_parent().find_child("WarpPoints", true, false)
\tif warp_container and warp_container.get_child_count() > 0:
\t\tvar first_warp: Node2D = warp_container.get_child(0) as Node2D
\t\tif first_warp:
\t\t\tplayer.global_position = first_warp.global_position
\t\t\tprint("[DebugSpawner] Player at warp: %s" % first_warp.name)
\telse:
\t\tvar dims := {map_dims}
\t\tplayer.global_position = Vector2(dims.x / 2.0, dims.y / 2.0)
\t\tprint("[DebugSpawner] Player at map center")

\tprint("[DebugSpawner] Standalone mode for: {map_info['root_name']}")
'''

    return script


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_debug_spawner.py /path/to/map.tscn [--player-scene res://path]")
        sys.exit(1)

    tscn_path = sys.argv[1]
    player_scene = "res://actors/player/Player.tscn"

    for i, arg in enumerate(sys.argv):
        if arg == "--player-scene" and i + 1 < len(sys.argv):
            player_scene = sys.argv[i + 1]

    if not os.path.isfile(tscn_path):
        print(f"Error: {tscn_path} not found")
        sys.exit(1)

    map_info = parse_map_metadata(tscn_path)
    print(f"Map: {map_info['root_name']}")
    print(f"Existing script: {map_info.get('root_script', 'none')}")
    print(f"Metadata: {map_info['metadata']}")

    script = generate_spawner_script(map_info, player_scene)

    # Write next to the .tscn
    output_dir = os.path.dirname(tscn_path)
    base_name = Path(tscn_path).stem
    output_path = os.path.join(output_dir, f"debug_spawner_{base_name}.gd")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(script)

    print(f"\nGenerated: {output_path}")

    if map_info.get("root_script"):
        print(f"\n⚠ The map root already has a script. Add a DebugSpawner child node")
        print(f"  and attach this script to it. See the generated file for instructions.")
    else:
        print(f"\nAttach this script to the \"{map_info['root_name']}\" root node.")
        print(f"It will auto-spawn a Player when running the scene standalone (F6).")


if __name__ == "__main__":
    main()
